insert into student(name, birthday, groupnumber)values('John','2002-03-10',1);
insert into student(name, birthday, groupnumber)values('Chris','2002-03-10',1);
insert into student(name, birthday, groupnumber)values('Carl','2002-03-10',1);
insert into student(name, birthday, groupnumber)values('Oliver','2002-03-10',2);
insert into student(name, birthday, groupnumber)values('James','2002-03-10',2);
insert into student(name, birthday, groupnumber)values('Lucas','2002-03-10',2);
insert into student(name, birthday, groupnumber)values('Henry','2002-03-10',2);
insert into student(name, birthday, groupnumber)values('Jacob','2002-03-10',3);
insert into student(name, birthday, groupnumber)values('Logan','2002-03-10',3);
insert into student(name, birthday, groupnumber)values('Koml','2002-03-10',4);
insert into student(name, birthday, groupnumber)values('Jobs','2002-03-10',4);
insert into student(name, birthday, groupnumber)values('Somon','2002-03-10',4);
insert into student(name, birthday, groupnumber)values('lehky','2002-03-10',5);
insert into student(name, birthday, groupnumber)values('Large','2002-03-10',5);
insert into student(name, birthday, groupnumber)values('Homom','2002-03-10',5);
insert into student(name, birthday, groupnumber)values('Jonny','2002-03-10',5);
insert into student(name, birthday, groupnumber)values('Salim','2005-03-10',5);
insert into subject(name, description, grade)values('art','science about Art',1);
insert into subject(name, description, grade)values('music','science about music',1);
insert into subject(name, description, grade)values('geography','science about Geography',2);
insert into subject(name, description, grade)values('history','science about history',2);
insert into subject(name, description, grade)values('pe','science about history',3);
insert into subject(name, description, grade)values('math','science about math',3);
insert into subject(name, description, grade)values('science','about science',4);
insert into subject(name, description, grade)values('it','about it science',4);
insert into subject(name, description, grade)values('philosophy','science about philosophy',5);
insert into subject(name, description, grade)values('chemical','about chemical science',5);
insert into subject(name, description, grade)values('psychology','about psychology science',5);
insert into paymenttype(name)value('DAILY');
insert into paymenttype(name)value('WEEKLY');
insert into paymenttype(name)value('MONTHLY');
insert into payment(type_id, amount, payment_date, student_id)values(2,500.45,'1970-08-01 21:00:00',1);
insert into payment(type_id, amount, payment_date, student_id)values(3,524.00,'2000-01-01 20:02:42',4);
insert into payment(type_id, amount, payment_date, student_id)values(2,452.25,'2001-01-01 09:10:58',7);
insert into payment(type_id, amount, payment_date, student_id)values(1,45.5442,'2002-01-01 00:09:10',5);
insert into payment(type_id, amount, payment_date, student_id)values(3,24.101,'2002-01-01 04:09:10',4);
insert into payment(type_id, amount, payment_date, student_id)values(1,124.101,'2002-01-01 00:09:10',2);
